# Generated by Django 4.2.5 on 2023-09-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
